### ISSUE TITLE
Feilmelding på sms Alver

### ISSUE THREAD

**Issue by geirsandvoll** [PorticoEstate/-Aktiv-Kommune-feil-forslag#13]
Skal sette opp sms funksjon for Alver kommune. Har lagt til smsalert i customconfig identisk som Stavanger har, slik vi har satt opp i andre instanser. 

Får derimot en feil når jeg prøver å komme inn på sms modulen, som jeg ikke helt finner ut av. 

<html>
<body>

27/09/2023 - 11:12:24 | geir.sandvoll.andersen | sms | Feil | /porticogit/4631/sms/inc/class.sms.inc.php | 54
-- | -- | -- | -- | -- | --
  | Uncaught Exception: ERROR: Gateway send module '99999999' does not exists - please contact system administrator #0 /porticogit/4631/phpgwapi/inc/common_functions.inc.php(208): require_once() #1 /porticogit/4631/phpgwapi/inc/class.object_factory.inc.php(80): include_class('sms', 'sms') #2 /porticogit/4631/phpgwapi/inc/common_functions.inc.php(248): phpgwapi_object_factory::createObject('sms', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_') #3 /porticogit/4631/sms/inc/class.bosms.inc.php(39): createObject('sms.sms') #4 /porticogit/4631/phpgwapi/inc/class.object_factory.inc.php(108) : eval()'d code(1): sms_bosms->__construct(false) #5 /porticogit/4631/phpgwapi/inc/class.object_factory.inc.php(108): eval() #6 /porticogit/4631/phpgwapi/inc/common_functions.inc.php(248): phpgwapi_object_factory::createObject('sms_bosms', false, '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_') #7 /porticogit/4631/sms/inc/class.uisms.inc.php(50): createObject('sms.bosms', false) #8 /porticogit/4631/phpgwapi/inc/class.object_factory.inc.php(90): sms_uisms->__construct() #9 /porticogit/4631/phpgwapi/inc/common_functions.inc.php(248): phpgwapi_object_factory::createObject('sms_uisms', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_', '_UNDEF_') #10 /porticogit/4631/index.php(94): createObject('sms.uisms') #11

</body>
</html>

**Comment by geirsandvoll** [comment]
Huskeliste til neste gang: når smsalert er lagt inn, oppdater common med modulen
